---
- name: Create encrypted ZFS datasets
  hosts: all
  become: true
  tasks:
    - name: Keeper login check (when using Keeper)
      block:
        - name: Expand Keeper config path for login check
          ansible.builtin.set_fact:
            keeper_config_expanded: "{{ (lookup('env', 'KEEPER_CONFIG_PATH') | length > 0) | ternary(lookup('env', 'KEEPER_CONFIG_PATH'), keeper_config_path | expanduser) }}"
          delegate_to: localhost
          become: false
          run_once: true

        - name: Verify Keeper is logged in
          ansible.builtin.command:
            cmd: keeper --config "{{ keeper_config_expanded }}" login-status
          delegate_to: localhost
          become: false
          run_once: true
          register: keeper_login_check
          changed_when: false
          failed_when: false

        - name: Fail if Keeper is not logged in
          ansible.builtin.fail:
            msg: "Keeper is not logged in. Run 'keeper login'. stdout: {{ keeper_login_check.stdout | default('') }}"
          when: keeper_login_check.rc != 0 or 'Logged in' not in (keeper_login_check.stdout | default(''))
          delegate_to: localhost
          become: false
          run_once: true
      when: vault_integration in ["keeper", "both"]

    - name: Install zfsutils-linux package
      ansible.builtin.apt:
        name: zfsutils-linux
        state: present
        update_cache: true

    - name: Check if ZFS key file exists
      ansible.builtin.stat:
        path: "{{ zfs_key_path }}"
      register: key_file

    # Only create a key if none exists; never overwrite an existing remote key
    - name: Create ZFS encryption key file
      ansible.builtin.shell:
        cmd: dd if=/dev/urandom of={{ zfs_key_path }} bs=32 count=1
      when: not key_file.stat.exists

    - name: Set key file permissions
      ansible.builtin.file:
        path: "{{ zfs_key_path }}"
        owner: root
        group: root
        mode: '0600'

    - name: Get list of existing ZFS datasets
      ansible.builtin.command:
        cmd: zfs list -H -o name
      register: existing_datasets
      changed_when: false

    - name: Create encrypted ZFS datasets
      ansible.builtin.command:
        cmd: >
          zfs create
          -o encryption=on
          -o keyformat=raw
          -o keylocation=file://{{ zfs_key_path }}
          {{ zpool_name }}/{{ item }}
      loop: "{{ zfs_datasets }}"
      when: (zpool_name + '/' + item) not in existing_datasets.stdout_lines

    - name: Ensure local key backup directory exists
      ansible.builtin.file:
        path: "{{ local_key_backup_dir }}"
        state: directory
        mode: '0700'
      delegate_to: localhost
      become: false
      run_once: true

    - name: Fetch key file to local backup
      ansible.builtin.fetch:
        src: "{{ zfs_key_path }}"
        dest: "{{ local_key_backup_dir }}/{{ inventory_hostname }}_zfs_drivekey.bin"
        flat: true
      register: fetch_result

    - name: Upload key to 1Password
      ansible.builtin.include_tasks: tasks/vault_upload_1password.yml
      when:
        - vault_integration in ["1password", "both"]
        - fetch_result is changed

    # When using Keeper: upload if new/updated key, and when datasets already exist
    # ensure the key is in Keeper (create record if missing).
    - name: Upload key to Keeper (or ensure existing key is in Keeper)
      ansible.builtin.include_tasks: tasks/vault_upload_keeper.yml
      when: vault_integration in ["keeper", "both"]
